name: tests

on:
  push:
    branches: [main, test-me-*]
    tags:
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    timeout-minutes: 10

    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          python: 3.9
        - os: ubuntu-latest
          python: '3.10'
        - os: ubuntu-latest
          python: '3.11'
        - os: ubuntu-latest
          python: '3.12'
        - os: macos-14
          python: 3.9
        - os: macos-14
          python: '3.10'
        - os: macos-14
          python: '3.11'
        - os: macos-14
          python: '3.12'
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install Dependencies
        run: |
          pip install --upgrade setuptools pip
          pip install .[dev]

      - name: Lint and Type Check
        run: pre-commit run --all-files

      - name: Run Single Simulation
        run: python run_single.py --total-time 1 --no-gui

      - name: Run Multiple Simulations
        run: python run_globus_compute.py --num-balls 16 --process-pool 4
